In [51]:
import pandas as pd

In [52]:
df = pd.read_csv(r"C:\Users\putna\Downloads\swiggy_demographic (1).csv")

In [53]:
df.head()

,rider_id,age,ratings,restaurant_latitude,restaurant_longitude,delivery_latitude,delivery_longitude,order_date,weather,traffic,...,time_taken,city_name,order_day,order_month,order_day_of_week,is_weekend,pickup_time_minutes,order_time_hour,order_time_of_day,distance
0,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,sunny,high,...,24,INDO,19,3,saturday,1,15.0,11.0,morning,3.025149
1,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,stormy,jam,...,33,BANG,25,3,friday,0,5.0,19.0,evening,20.183530
2,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,sandstorms,low,...,26,BANG,19,3,saturday,1,15.0,8.0,morning,1.552758
3,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,sunny,medium,...,21,COIMB,5,4,tuesday,0,10.0,18.0,evening,7.790401
4,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,cloudy,high,...,30,CHEN,26,3,saturday,1,15.0,13.0,afternoon,6.210138

In [54]:
corr = df.corr(numeric_only=True)
print(corr['time_taken'].sort_values(ascending=False))

time_taken              1.000000
multiple_deliveries     0.387231
distance                0.320705
age                     0.303817
order_time_hour         0.184378
order_day               0.023676
delivery_latitude       0.013964
restaurant_latitude     0.011813
delivery_longitude      0.010084
restaurant_longitude    0.006720
is_weekend             -0.003141
pickup_time_minutes    -0.008478
order_month            -0.012354
vehicle_condition      -0.235125
ratings                -0.360980
Name: time_taken, dtype: float64

## Target feature

In [55]:
X = df.drop('time_taken', axis=1)
y = df['time_taken']

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45502 entries, 0 to 45501
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   rider_id              45502 non-null  object
 1   age                   43648 non-null  float64
 2   ratings               43594 non-null  float64
 3   restaurant_latitude   41872 non-null  float64
 4   restaurant_longitude  41872 non-null  float64
 5   delivery_latitude     41872 non-null  float64
 6   delivery_longitude    41872 non-null  float64
 7   order_date            45502 non-null  object
 8   weather               44977 non-null  object
 9   traffic               44992 non-null  object
 10  vehicle_condition     45502 non-null  int64
 11  type_of_order         45502 non-null  object
 12  type_of_vehicle       45502 non-null  object
 13  multiple_deliveries   44509 non-null  float64
 14  festival              45274 non-null  object
 15  city_type             44304 non-null  object
 16  time_taken            45502 non-null  int64
 17  city_name             45502 non-null  object
 18  order_day             45502 non-null  int64
 19  order_month           45502 non-null  int64
 20  order_day_of_week     45502 non-null  object
 21  is_weekend            45502 non-null  int64
 22  pickup_time_minutes   43862 non-null  float64
 23  order_time_hour       43862 non-null  float64
 24  order_time_of_day     45502 non-null  object
 25  distance              41872 non-null  float64
dtypes: float64(10), int64(5), object(11)
memory usage: 9.0+ MB

In [57]:
X

,rider_id,age,ratings,restaurant_latitude,restaurant_longitude,delivery_latitude,delivery_longitude,order_date,weather,traffic,...,city_type,city_name,order_day,order_month,order_day_of_week,is_weekend,pickup_time_minutes,order_time_hour,order_time_of_day,distance
0,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,sunny,high,...,urban,INDO,19,3,saturday,1,15.0,11.0,morning,3.025149
1,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,stormy,jam,...,metropolitian,BANG,25,3,friday,0,5.0,19.0,evening,20.183530
2,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,sandstorms,low,...,urban,BANG,19,3,saturday,1,15.0,8.0,morning,1.552758
3,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,sunny,medium,...,metropolitian,COIMB,5,4,tuesday,0,10.0,18.0,evening,7.790401
4,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,cloudy,high,...,metropolitian,CHEN,26,3,saturday,1,15.0,13.0,afternoon,6.210138
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45497,JAPRES04DEL01,30.0,4.8,26.902328,75.794257,26.912328,75.804257,2022-03-24,windy,high,...,metropolitian,JAP,24,3,thursday,0,10.0,11.0,morning,1.489846
45498,AGRRES16DEL01,21.0,4.6,NaN,NaN,NaN,NaN,2022-02-16,windy,jam,...,metropolitian,AGR,16,2,wednesday,0,15.0,19.0,evening,NaN
45499,CHENRES08DEL03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,2022-03-11,cloudy,low,...,metropolitian,CHEN,11,3,friday,0,15.0,23.0,night,4.657195
45500,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,2022-03-07,cloudy,high,...,metropolitian,COIMB,7,3,monday,0,5.0,13.0,afternoon,6.232393
45501,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,2022-03-02,fog,medium,...,metropolitian,RANCHI,2,3,wednesday,0,5.0,17.0,evening,12.074396

In [58]:
X.isnull().sum()

rider_id                   0
age                     1854
ratings                 1908
restaurant_latitude     3630
restaurant_longitude    3630
delivery_latitude       3630
delivery_longitude      3630
order_date                 0
weather                  525
traffic                  510
vehicle_condition          0
type_of_order              0
type_of_vehicle            0
multiple_deliveries      993
festival                 228
city_type               1198
city_name                  0
order_day                  0
order_month                0
order_day_of_week          0
is_weekend                 0
pickup_time_minutes     1640
order_time_hour         1640
order_time_of_day          0
distance                3630
dtype: int64

In [59]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45502 entries, 0 to 45501
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   rider_id              45502 non-null  object
 1   age                   43648 non-null  float64
 2   ratings               43594 non-null  float64
 3   restaurant_latitude   41872 non-null  float64
 4   restaurant_longitude  41872 non-null  float64
 5   delivery_latitude     41872 non-null  float64
 6   delivery_longitude    41872 non-null  float64
 7   order_date            45502 non-null  object
 8   weather               44977 non-null  object
 9   traffic               44992 non-null  object
 10  vehicle_condition     45502 non-null  int64
 11  type_of_order         45502 non-null  object
 12  type_of_vehicle       45502 non-null  object
 13  multiple_deliveries   44509 non-null  float64
 14  festival              45274 non-null  object
 15  city_type             44304 non-null  object
 16  city_name             45502 non-null  object
 17  order_day             45502 non-null  int64
 18  order_month           45502 non-null  int64
 19  order_day_of_week     45502 non-null  object
 20  is_weekend            45502 non-null  int64
 21  pickup_time_minutes   43862 non-null  float64
 22  order_time_hour       43862 non-null  float64
 23  order_time_of_day     45502 non-null  object
 24  distance              41872 non-null  float64
dtypes: float64(10), int64(4), object(11)
memory usage: 8.7+ MB

## handling missing values

In [60]:
X.isnull().sum()

rider_id                   0
age                     1854
ratings                 1908
restaurant_latitude     3630
restaurant_longitude    3630
delivery_latitude       3630
delivery_longitude      3630
order_date                 0
weather                  525
traffic                  510
vehicle_condition          0
type_of_order              0
type_of_vehicle            0
multiple_deliveries      993
festival                 228
city_type               1198
city_name                  0
order_day                  0
order_month                0
order_day_of_week          0
is_weekend                 0
pickup_time_minutes     1640
order_time_hour         1640
order_time_of_day          0
distance                3630
dtype: int64

In [61]:
# Select numerical columns
num_cols = X.select_dtypes(include=['int64', 'float64']).columns

In [62]:
# Fill missing values in numerical columns with median
X[num_cols] = X[num_cols].fillna(X[num_cols].median())

In [63]:
# Select categorical columns
cat_cols = X.select_dtypes(include=['object', 'string', 'category']).columns

In [64]:
# Fill missing values in categorical columns with mode
for col in cat_cols:
    X[col] = X[col].fillna(X[col].mode()[0])

In [65]:
X.isnull().sum()

rider_id                0
age                     0
ratings                 0
restaurant_latitude     0
restaurant_longitude    0
delivery_latitude       0
delivery_longitude      0
order_date              0
weather                 0
traffic                 0
vehicle_condition       0
type_of_order           0
type_of_vehicle         0
multiple_deliveries     0
festival                0
city_type               0
city_name               0
order_day               0
order_month             0
order_day_of_week       0
is_weekend              0
pickup_time_minutes     0
order_time_hour         0
order_time_of_day       0
distance                0
dtype: int64

## Removing irrelevent columns

In [66]:
cols_to_drop = [
    'rider_id',
    'order_date',
    'restaurant_latitude',
    'restaurant_longitude',
    'delivery_latitude',
    'delivery_longitude',
    'order_day',
    'order_month'
]


X = X.drop(columns=cols_to_drop, errors='ignore')

In [67]:
X.columns

Index(['age', 'ratings', 'weather', 'traffic', 'vehicle_condition',
       'type_of_order', 'type_of_vehicle', 'multiple_deliveries', 'festival',
       'city_type', 'city_name', 'order_day_of_week', 'is_weekend',
       'pickup_time_minutes', 'order_time_hour', 'order_time_of_day',
       'distance'],
      dtype='object')

## Feature segregation

In [68]:
Nominal_cols = [
    'weather',
    'festival',
    'city_type',
    'type_of_order',
    'type_of_vehicle',
    'order_time_of_day',
    'order_day_of_week',
    'city_name'
]

Ordinal_cols = [
    'traffic'
]

Numerical_cols = [
    'age',
    'ratings',
    'vehicle_condition',
    'multiple_deliveries',
    'pickup_time_minutes',
    'order_time_hour',
    'distance',
    'is_weekend',
]

In [69]:
# ✅ FORCE CORRECT DATA TYPES (ADD THIS)
for col in Nominal_cols + Ordinal_cols:
    X[col] = X[col].astype(str)

for col in Numerical_cols:
    X[col] = pd.to_numeric(X[col], errors='coerce')

## Data Preprocessing

In [125]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder, PowerTransformer
from sklearn.impute import SimpleImputer



# -------------------- Pipelines --------------------
num_pipeline = Pipeline([
    ('Feature scaling', StandardScaler()),
    ('Feature Transformation', PowerTransformer(method='yeo-johnson'))
])

ord_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),  
    ('encoder', OrdinalEncoder(
        categories=[['low','medium','high','jam']],
        handle_unknown='use_encoded_value',
        unknown_value=-1
    ))
])

nom_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),  # fill missing strings
    ('onehot', OneHotEncoder(drop='first', handle_unknown='ignore'))
])

# -------------------- Column Transformer --------------------
Datapreprocessing = ColumnTransformer([
    ('Num', num_pipeline, Numerical_cols),
    ('Ord', ord_pipeline, Ordinal_cols),
    ('Nom', nom_pipeline, Nominal_cols)
])

In [126]:
Datapreprocessing

ColumnTransformer(transformers=[('Num',
                                 Pipeline(steps=[('Feature scaling',
                                                  StandardScaler()),
                                                 ('Feature Transformation',
                                                  PowerTransformer())]),
                                 ['age', 'ratings', 'vehicle_condition',
                                  'multiple_deliveries', 'pickup_time_minutes',
                                  'order_time_hour', 'distance',
                                  'is_weekend']),
                                ('Ord',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  O...
                                                                              'jam']],
                                                                 handle_unknown='use_encoded_value',
                                                                 unknown_value=-1))]),
                                 ['traffic']),
                                ('Nom',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'))]),
                                 ['weather', 'festival', 'city_type',
                                  'type_of_order', 'type_of_vehicle',
                                  'order_time_of_day', 'order_day_of_week',
                                  'city_name'])])

In [73]:
# testing 
Datapreprocessing.fit_transform(X_train)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 519217 stored elements and shape (36401, 54)>

In [74]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45502 entries, 0 to 45501
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  45502 non-null  float64
 1   ratings              45502 non-null  float64
 2   weather              45502 non-null  object
 3   traffic              45502 non-null  object
 4   vehicle_condition    45502 non-null  int64
 5   type_of_order        45502 non-null  object
 6   type_of_vehicle      45502 non-null  object
 7   multiple_deliveries  45502 non-null  float64
 8   festival             45502 non-null  object
 9   city_type            45502 non-null  object
 10  city_name            45502 non-null  object
 11  order_day_of_week    45502 non-null  object
 12  is_weekend           45502 non-null  int64
 13  pickup_time_minutes  45502 non-null  float64
 14  order_time_hour      45502 non-null  float64
 15  order_time_of_day    45502 non-null  object
 16  distance             45502 non-null  float64
dtypes: float64(6), int64(2), object(9)
memory usage: 5.9+ MB

## Column names mismatch check

In [76]:
print("Train columns:", list(X_train.columns))
print("Test columns:", list(X_test.columns))

Train columns: ['age', 'ratings', 'weather', 'traffic', 'vehicle_condition', 'type_of_order', 'type_of_vehicle', 'multiple_deliveries', 'festival', 'city_type', 'city_name', 'order_day_of_week', 'is_weekend', 'pickup_time_minutes', 'order_time_hour', 'order_time_of_day', 'distance']
Test columns: ['age', 'ratings', 'weather', 'traffic', 'vehicle_condition', 'type_of_order', 'type_of_vehicle', 'multiple_deliveries', 'festival', 'city_type', 'city_name', 'order_day_of_week', 'is_weekend', 'pickup_time_minutes', 'order_time_hour', 'order_time_of_day', 'distance']

In [81]:
# data types
print(X_train.dtypes)

age                    float64
ratings                float64
weather                 object
traffic                 object
vehicle_condition        int64
type_of_order           object
type_of_vehicle         object
multiple_deliveries    float64
festival                object
city_type               object
city_name               object
order_day_of_week       object
is_weekend               int64
pickup_time_minutes    float64
order_time_hour        float64
order_time_of_day       object
distance               float64
dtype: object

In [82]:
X['multiple_deliveries'] = X['multiple_deliveries'].astype(int)
X_train['multiple_deliveries'] = X_train['multiple_deliveries'].astype(int)
X_test['multiple_deliveries'] = X_test['multiple_deliveries'].astype(int)

In [85]:
# data types
print(X_test.dtypes)

age                    float64
ratings                float64
weather                 object
traffic                 object
vehicle_condition        int64
type_of_order           object
type_of_vehicle         object
multiple_deliveries      int64
festival                object
city_type               object
city_name               object
order_day_of_week       object
is_weekend               int64
pickup_time_minutes    float64
order_time_hour        float64
order_time_of_day       object
distance               float64
dtype: object

## train the model

In [86]:
from sklearn.model_selection import train_test_split

In [87]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=23
)

In [88]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score,root_mean_squared_error
import numpy as np

## KNN

In [89]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score,root_mean_squared_error

knn_model = Pipeline([
('Datapreprocessing',Datapreprocessing),
('Algorithm',KNeighborsRegressor(n_neighbors=5))
])

knn_model.fit(X_train,y_train)

y_pred= knn_model.predict(X_test)
mse_knn = mean_squared_error(y_test , y_pred)
mae_knn = mean_absolute_error(y_test , y_pred)
r2_knn = r2_score(y_test , y_pred)
rmse_knn = root_mean_squared_error(y_test , y_pred)

print("\nKNN")
print('MSE: ',mse_knn)
print('MAE:',mae_knn)
print('r2:',r2_knn)
print('RMSE:',rmse_knn)

KNN
MSE:  35.08571805296121
MAE: 4.6327656301505336
r2: 0.6053806585520887
RMSE: 5.9233198506379185

## linear Regression

In [90]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score,root_mean_squared_error
import numpy as np
lr_model = Pipeline([
    ('Datapreprocessing', Datapreprocessing),
    ('Algorithm', LinearRegression())
])

lr_model.fit(X_train, y_train)

y_pred = lr_model.predict(X_test)

mse_lr = mean_squared_error(y_test, y_pred)
mae_lr = mean_absolute_error(y_test, y_pred)
r2_lr = r2_score(y_test, y_pred)
rmse_lr = np.sqrt(mse_lr)

print("\nLinear Regression")
print('MSE:', mse_lr)
print('MAE:', mae_lr)
print('R2:', r2_lr)
print('RMSE:', rmse_lr)

Linear Regression
MSE: 37.86146635818767
MAE: 4.917310358260233
R2: 0.5741610048291639
RMSE: 6.153167181069247

## Random forest

In [91]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score,root_mean_squared_error


rf_model = Pipeline([
    ('Datapreprocessing', Datapreprocessing),
    ('Algorithm', RandomForestRegressor(
        n_estimators=50,
        max_depth=10,
        n_jobs=-1,
        max_samples=0.8,
        random_state=42
    ))
])

rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)


mse_rf = mean_squared_error(y_test, y_pred)
mae_rf = mean_absolute_error(y_test, y_pred)
r2_rf = r2_score(y_test, y_pred)
rmse_rf = np.sqrt(mse_rf)

print("\nRandom Forest")
print('MSE:', mse_rf)
print('MAE:', mae_rf)
print('R2:', r2_rf)
print('RMSE:', rmse_rf)

Random Forest
MSE: 20.182471692028678
MAE: 3.5413905835831105
R2: 0.7730018329430405
RMSE: 4.49249058897497

## decision tree

In [93]:
from sklearn.tree import DecisionTreeRegressor

dt_model = Pipeline([
    ('Datapreprocessing', Datapreprocessing),
    ('Algorithm', DecisionTreeRegressor())
])

dt_model.fit(X_train, y_train)

y_pred = dt_model.predict(X_test)

mse_dt = mean_squared_error(y_test, y_pred)
mae_dt = mean_absolute_error(y_test, y_pred)
r2_dt = r2_score(y_test, y_pred)
rmse_dt = np.sqrt(mse_dt)

print("\nDecision Tree")
print('MSE:', mse_dt)
print('MAE:', mae_dt)
print('R2:', r2_dt)
print('RMSE:', rmse_dt)

Decision Tree
MSE: 31.864850016481704
MAE: 4.267662894187452
R2: 0.6416067041905902
RMSE: 5.6448959260983465

In [94]:
#!pip install xgboost

## XGBoost

In [127]:
from xgboost import XGBRegressor

from xgboost import XGBRegressor
xgb_model = Pipeline([
    ('preprocessing', Datapreprocessing),
    ('Algorithm', XGBRegressor(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=6,
        random_state=23
    ))
])


xgb_model.fit(X_train, y_train)

y_pred = xgb_model.predict(X_test)

mse_xgb = mean_squared_error(y_test, y_pred)
mae_xgb = mean_absolute_error(y_test, y_pred)
r2_xgb = r2_score(y_test, y_pred)
rmse_xgb = np.sqrt(mse_xgb)

print("\nXGBoost")
print('MSE:', mse_xgb)
print('MAE:', mae_xgb)
print('R2:', r2_xgb)
print('RMSE:', rmse_xgb)

XGBoost
MSE: 16.831485748291016
MAE: 3.2692816257476807
R2: 0.8106913566589355
RMSE: 4.102619376482665

## Gradient Boosting

In [96]:
from sklearn.ensemble import GradientBoostingRegressor

gb_model = Pipeline([
    ('Datapreprocessing', Datapreprocessing),
    ('Algorithm', GradientBoostingRegressor())
])

gb_model.fit(X_train, y_train)

y_pred = gb_model.predict(X_test)

mse_gb = mean_squared_error(y_test, y_pred)
mae_gb = mean_absolute_error(y_test, y_pred)
r2_gb = r2_score(y_test, y_pred)
rmse_gb = np.sqrt(mse_gb)

print("\nGradient Boosting")
print('MSE:', mse_gb)
print('MAE:', mae_gb)
print('R2:', r2_gb)
print('RMSE:', rmse_gb)

Gradient Boosting
MSE: 21.907145521367568
MAE: 3.746131679753569
R2: 0.7536039215273806
RMSE: 4.680506972686566

## suppor vector regression

In [97]:
from sklearn.svm import SVR

svr_model = Pipeline([
    ('Datapreprocessing', Datapreprocessing),
    ('Algorithm', SVR())
])

svr_model.fit(X_train, y_train)

y_pred = svr_model.predict(X_test)

mse_svr = mean_squared_error(y_test, y_pred)
mae_svr = mean_absolute_error(y_test, y_pred)
r2_svr = r2_score(y_test, y_pred)
rmse_svr = np.sqrt(mse_svr)

print("\nSVR")
print('MSE:', mse_svr)
print('MAE:', mae_svr)
print('R2:', r2_svr)
print('RMSE:', rmse_svr)

SVR
MSE: 25.692260660915
MAE: 4.011081445277631
R2: 0.7110316235508065
RMSE: 5.068753363590993

## final result

In [104]:
import pandas as pd

results = {
    "Model": ["KNN", "Linear", "DecisionTree", "RandomForest", "GradientBoost", "SVR", "XGBoost"],
    
    "R2 Score": [r2_knn, r2_lr, r2_dt, r2_rf, r2_gb, r2_svr, r2_xgb],
    
    "RMSE": [rmse_knn, rmse_lr, rmse_dt, rmse_rf, rmse_gb, rmse_svr, rmse_xgb],
    
    "MAE": [mae_knn, mae_lr, mae_dt, mae_rf, mae_gb, mae_svr, mae_xgb]
}

df_results = pd.DataFrame(results)

# Sort by best model
df_results = df_results.sort_values(by="R2 Score", ascending=False)

print(df_results)

           Model  R2 Score      RMSE       MAE
6        XGBoost  0.810691  4.102619  3.269282
3   RandomForest  0.773002  4.492491  3.541391
4  GradientBoost  0.753604  4.680507  3.746132
5            SVR  0.711032  5.068753  4.011081
2   DecisionTree  0.641607  5.644896  4.267663
0            KNN  0.605381  5.923320  4.632766
1         Linear  0.574161  6.153167  4.917310

## Overfitting checking

In [99]:
train_pred = xgb_model.predict(X_train)
print("Train R2:", r2_score(y_train, train_pred))

# Test score
test_pred = xgb_model.predict(X_test)
print("Test R2:", r2_score(y_test, test_pred))

Train R2: 0.8317341804504395
Test R2: 0.8106913566589355

## cross validation techniques

## K-Fold cross validation

In [100]:
from sklearn.model_selection import KFold, cross_val_score
import numpy as np

# K-Fold setup
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# Cross Validation (R2)
r2_scores = cross_val_score(xgb_model, X, y, cv=kf, scoring='r2')

print("R2 scores for each fold:", r2_scores)
print("Mean R2:", np.mean(r2_scores))
print("Std Dev:", np.std(r2_scores))

R2 scores for each fold: [0.80603266 0.80836248 0.80689496 0.80903435 0.80517507]
Mean R2: 0.8070999026298523
Std Dev: 0.0014298390832820547

## Hyperparametter Tuning

## Randomized search cv

In [101]:
from sklearn.model_selection import RandomizedSearchCV
from xgboost import XGBRegressor
from sklearn.pipeline import Pipeline

# Pipeline
xgb_pipeline = Pipeline([
    ('preprocessing', Datapreprocessing),   # your preprocessor name
    ('model', XGBRegressor(random_state=23))
])

# Parameter Distribution
param_dist = {
    'model__n_estimators': [200, 300],
    'model__learning_rate': [0.01, 0.03, 0.05],
    'model__max_depth': [3, 4, 5],
    'model__subsample': [0.7, 0.8],
    'model__colsample_bytree': [0.7, 0.8],
    'model__gamma': [0.2, 0.3, 0.5],
    'model__min_child_weight': [5, 7, 10],
    'model__reg_alpha': [0, 0.1, 1],
    'model__reg_lambda': [1, 5, 10]
}

# Randomized Search
random_search = RandomizedSearchCV(
    estimator=xgb_pipeline,
    param_distributions=param_dist,
    n_iter=15,              # reduced (safe for laptop)
    cv=5,
    scoring='r2',
    verbose=2,
    n_jobs=2,               # ⚠️ important (avoid crash)
    random_state=42
)

# Fit
random_search.fit(X_train, y_train)

# Best Results
print("Best Parameters:", random_search.best_params_)
print("Best CV R2:", random_search.best_score_)

Fitting 5 folds for each of 15 candidates, totalling 75 fits
Best Parameters: {'model__subsample': 0.7, 'model__reg_lambda': 10, 'model__reg_alpha': 0.1, 'model__n_estimators': 200, 'model__min_child_weight': 5, 'model__max_depth': 5, 'model__learning_rate': 0.05, 'model__gamma': 0.5, 'model__colsample_bytree': 0.8}
Best CV R2: 0.7878140926361084

In [102]:
best_model = random_search.best_estimator_

y_pred = best_model.predict(X_test)

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import numpy as np

print("Final R2:", r2_score(y_test, y_pred))
print("Final RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("Final MAE:", mean_absolute_error(y_test, y_pred))

Final R2: 0.7959111928939819
Final RMSE: 4.259764281722622
Final MAE: 3.3910250663757324

## gridsearchcv

In [128]:
from sklearn.model_selection import GridSearchCV
from xgboost import XGBRegressor
from sklearn.pipeline import Pipeline

# Pipeline
xgb_pipeline = Pipeline([
    ('preprocessing', Datapreprocessing),
    ('model', XGBRegressor(random_state=42))
])

# Param Grid (small & focused ⚠️)
param_grid = {
    'model__n_estimators': [200, 300],
    'model__learning_rate': [0.05, 0.1],
    'model__max_depth': [5, 6, 7],
    'model__subsample': [0.8, 1.0],
    'model__colsample_bytree': [0.8, 1.0]
}

# Grid Search
grid_search = GridSearchCV(
    estimator=xgb_pipeline,
    param_grid=param_grid,
    cv=5,
    scoring='r2',
    verbose=2,
    n_jobs=2   # ⚠️ avoid crash
)

# Fit
grid_search.fit(X_train, y_train)

# Best Results
print("Best Parameters:", grid_search.best_params_)
print("Best CV R2:", grid_search.best_score_)

Fitting 5 folds for each of 48 candidates, totalling 240 fits
Best Parameters: {'model__colsample_bytree': 0.8, 'model__learning_rate': 0.05, 'model__max_depth': 7, 'model__n_estimators': 300, 'model__subsample': 1.0}
Best CV R2: 0.80913165807724

In [129]:
best_model2 = grid_search.best_estimator_

y_pred = best_model2.predict(X_test)

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import numpy as np

print("Final R2:", r2_score(y_test, y_pred))
print("Final RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("Final MAE:", mean_absolute_error(y_test, y_pred))

Final R2: 0.8161278963088989
Final RMSE: 4.04328081336404
Final MAE: 3.2199296951293945

## overfitting checking

In [106]:
train_pred = best_model2.predict(X_train)

from sklearn.metrics import r2_score

train_r2 = r2_score(y_train, train_pred)
test_r2 = r2_score(y_test, y_pred)

print("Train R2:", train_r2)
print("Test R2:", test_r2)

Train R2: 0.8557783365249634
Test R2: 0.8161278963088989

## best model

In [130]:
model = grid_search.best_estimator_
model

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('Num',
                                                  Pipeline(steps=[('Feature '
                                                                   'scaling',
                                                                   StandardScaler()),
                                                                  ('Feature '
                                                                   'Transformation',
                                                                   PowerTransformer())]),
                                                  ['age', 'ratings',
                                                   'vehicle_condition',
                                                   'multiple_deliveries',
                                                   'pickup_time_minutes',
                                                   'order_time_hour',
                                                   'distance', 'is_weekend']),
                                                 ('Ord',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(st...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.05,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=7, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=300, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [117]:
X['traffic'].unique()

array(['high', 'jam', 'low', 'medium'], dtype=object)

## input

In [131]:
import pandas as pd

def prepare_input(distance, traffic, pickup_time):
    """
    traffic must be one of: 'low', 'medium', 'high', 'jam'
    """
    # ✅ FIX: Validate traffic input - must be string category, not int
    valid_traffic = ['low', 'medium', 'high', 'jam']
    if traffic not in valid_traffic:
        raise ValueError(f"traffic must be one of {valid_traffic}, got '{traffic}'")
    
    return pd.DataFrame([{
        'distance': distance,
        'traffic': traffic,          # ✅ Must be string: 'low','medium','high','jam'
        'pickup_time_minutes': pickup_time,

        # default values
        'age': 30,
        'ratings': 4.2,
        'vehicle_condition': 2,
        'multiple_deliveries': 1,
        'order_time_hour': 20.0,
        'weather': 'sunny',
        'festival': 'No',
        'city_type': 'urban',
        'type_of_order': 'Meal',
        'type_of_vehicle': 'motorcycle',
        'order_time_of_day': 'evening',
        'order_day_of_week': 'friday',
        'is_weekend': 0
    }])

In [132]:
# ✅ FIX: Pass traffic as valid string category, NOT as integer string '2'
# Valid options: 'low', 'medium', 'high', 'jam'

model = grid_search.best_estimator_

input_df = prepare_input(5,'high', 15)   # ✅ FIXED: 'high' instead of '2'

# separate numeric and categorical columns
num_cols = X_train.select_dtypes(include=['int64','float64']).columns
cat_cols = X_train.select_dtypes(include=['object']).columns

# fill missing columns with appropriate types
for col in X_train.columns:
    if col not in input_df.columns:
        if col in num_cols:
            input_df[col] = 0
        else:
            # pick most frequent category from training
            input_df[col] = X_train[col].mode()[0]

# reorder columns
input_df = input_df[X_train.columns]

# now predict safely
prediction = model.predict(input_df)
print("Estimated Delivery Time:", round(prediction[0], 2), "minutes")

Estimated Delivery Time: 31.04 minutes

C:\Users\putna\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [1, 3] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

## prediction range

In [133]:
prediction = model.predict(input_df)[0]

# Range (±10%)
lower = prediction * 0.9
upper = prediction * 1.1

print(f"Estimated Delivery Time: {prediction:.2f} minutes")
print(f"Range: {lower:.2f} to {upper:.2f} minutes")

Estimated Delivery Time: 31.04 minutes
Range: 27.94 to 34.14 minutes

C:\Users\putna\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [1, 3] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

## Model confidence

In [134]:
prediction = model.predict(input_df)[0]

rmse = 4.6   # your model RMSE

confidence = 1 - (rmse / prediction)
confidence = max(0, min(1, confidence))

print("Confidence:", round(confidence*100, 2), "%")

Confidence: 85.18 %

C:\Users\putna\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [1, 3] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

## Create pickel file1

In [136]:
import pickle

model = random_search.best_estimator_

with open('delivery_time_model1.pkl', 'wb') as f:
    pickle.dump(model, f)